[package]
name = "async-session"
version = "1.0.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/http-rs/async-session"
documentation = "https://docs.rs/async-session"
description = "Async session support with pluggable middleware"
readme = "README.md"
edition = "2018"
keywords = []
categories = []
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>"
]

[features]

[dependencies]
async-trait = "0.1.24"
async-std = "1.5.0"
cookie = "0.13.3"
uuid = {version = "0.8.1", features = ["v4"] }

[dev-dependencies]
tide = "0.6.0"
